#!/bin/sh

#SBATCH --job-name=chempcpd
#SBATCH --time=4-00:00:00
#SBATCH --mail-type=ALL
#SBATCH --mail-user=antoine.schneeberger@lam.fr
#SBATCH --partition=seq
#SBATCH --output=resultslumr.log


 ulimit -s unlimited 
 ulimit -n 100240
 ulimit -u 95679
 ulimit -f unlimited
 ulimit -v unlimited
 ulimit -x unlimited

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/apps/intel/impi/2019.3.199/intel64/lib/:/lib64/:/libraries/libcalcul/netcdf/lib/
 
export NETCDF=/libraries/libcalcul/netcdf/
source /apps/intel/bin/ifortvars.sh intel64
source /apps/intel/bin/iccvars.sh intel64

echo 'ok'

path=/home/aschneeberger
cd $path 

source virtualenvwrapper.sh
workon chemcpd36

echo 'ok'

export OMP_NUM_THREAD=4

srun --ntasks 1 /home/aschneeberger/chemcpd/src/chemcpd.exe
