#!/bin/sh
#SBATCH -J chemcpd                            # run's name
#SBATCH -N 1                                    # request 1 node 
#SBATCH -c 1                                    # request 1 cpu per task
#SBATCH --mem=1GB                               # request 10GB
#SBATCH -t 5-00:00:00                           # request 12 hours walltime
#SBATCH -o Out.txt                              # output file name
#SBATCH -e Err.txt                              # error file name
#SBATCH --mail-type=BEGIN,END,FAIL              # send me an e-mail at beginning and end of the job
#SBATCH --mail-user=antoine.schneeberger@lam.fr
#SBATCH -p batch                                # Using the Batch partition to have 6 days of  walltime 



scl enable gcc-toolset-11 bash 
make 

path=$HOME
cd $path

$HOME/chemcpd/chemcpd.exe